import 'package:batch_or/hotel_model/hotel_class.dart';

List<List>difhot=[
 [
HotelClass(
name: 'Amkora',
abt: '',
price: '',
imgurl: 'assets/image/bhotel/amkora/1.webp',
location: 'Bhumthang,Bhutan',
review: '',
imgurl2: 'assets/image/bhotel/amkora/2.webp',
imgurl3: 'assets/image/bhotel/amkora/3.webp',
imgurl4: 'assets/image/bhotel/amkora/4.webp'),
HotelClass(
name: 'Hotel Ugyenling',
abt: '',
price: '',
imgurl: 'assets/image/bhotel/ugyenling/1.webp',
location: 'Bhumthang,Bhutan',
review: '',
imgurl2: 'assets/image/bhotel/ugyenling/2.webp',
imgurl3: 'assets/image/bhotel/ugyenling/3.webp',
imgurl4: 'assets/image/bhotel/ugyenling/4.webp'),
HotelClass(
name: 'Valley Resort',
abt: '',
price: '',
imgurl: 'assets/image/bhotel/valley/1.webp',
location: 'Bhumthang,Bhutan',
review: '',
imgurl2: 'assets/image/bhotel/valley/2.webp',
imgurl3: 'assets/image/bhotel/valley/3.webp',
imgurl4: 'assets/image/bhotel/valley/4.webp'),
HotelClass(
name: ' Hotel Yugharling',
abt: '',
price: '',
imgurl: 'assets/image/bhotel/yugharling/1.webp',
location: '',
review: '',
imgurl2: 'assets/image/bhotel/yugharling/2.webp',
imgurl3: 'assets/image/bhotel/yugharling/3.webp',
imgurl4: 'assets/image/bhotel/yugharling/4.webp'),

],
  [
    HotelClass(
        name: 'Amkora',
        abt: '',
        price: '',
        imgurl: 'assets/image/bhotel/amkora/1.webp',
        location: 'Bhumthang,Bhutan',
        review: '',
        imgurl2: 'assets/image/bhotel/amkora/2.webp',
        imgurl3: 'assets/image/bhotel/amkora/3.webp',
        imgurl4: 'assets/image/bhotel/amkora/4.webp'),
    HotelClass(
        name: 'Hotel Ugyenling',
        abt: '',
        price: '',
        imgurl: 'assets/image/bhotel/ugyenling/1.webp',
        location: 'Bhumthang,Bhutan',
        review: '',
        imgurl2: 'assets/image/bhotel/ugyenling/2.webp',
        imgurl3: 'assets/image/bhotel/ugyenling/3.webp',
        imgurl4: 'assets/image/bhotel/ugyenling/4.webp'),
    HotelClass(
        name: 'Valley Resort',
        abt: '',
        price: '',
        imgurl: 'assets/image/bhotel/valley/1.webp',
        location: 'Bhumthang,Bhutan',
        review: '',
        imgurl2: 'assets/image/bhotel/valley/2.webp',
        imgurl3: 'assets/image/bhotel/valley/3.webp',
        imgurl4: 'assets/image/bhotel/valley/4.webp'),
    HotelClass(
        name: ' Hotel Yugharling',
        abt: '',
        price: '',
        imgurl: 'assets/image/bhotel/yugharling/1.webp',
        location: '',
        review: '',
        imgurl2: 'assets/image/bhotel/yugharling/2.webp',
        imgurl3: 'assets/image/bhotel/yugharling/3.webp',
        imgurl4: 'assets/image/bhotel/yugharling/4.webp'),

  ],
  [
    HotelClass(
        name: 'Amkora',
        abt: '',
        price: '',
        imgurl: 'assets/image/bhotel/amkora/1.webp',
        location: 'Bhumthang,Bhutan',
        review: '',
        imgurl2: 'assets/image/bhotel/amkora/2.webp',
        imgurl3: 'assets/image/bhotel/amkora/3.webp',
        imgurl4: 'assets/image/bhotel/amkora/4.webp'),
    HotelClass(
        name: 'Hotel Ugyenling',
        abt: '',
        price: '',
        imgurl: 'assets/image/bhotel/ugyenling/1.webp',
        location: 'Bhumthang,Bhutan',
        review: '',
        imgurl2: 'assets/image/bhotel/ugyenling/2.webp',
        imgurl3: 'assets/image/bhotel/ugyenling/3.webp',
        imgurl4: 'assets/image/bhotel/ugyenling/4.webp'),
    HotelClass(
        name: 'Valley Resort',
        abt: '',
        price: '',
        imgurl: 'assets/image/bhotel/valley/1.webp',
        location: 'Bhumthang,Bhutan',
        review: '',
        imgurl2: 'assets/image/bhotel/valley/2.webp',
        imgurl3: 'assets/image/bhotel/valley/3.webp',
        imgurl4: 'assets/image/bhotel/valley/4.webp'),
    HotelClass(
        name: ' Hotel Yugharling',
        abt: '',
        price: '',
        imgurl: 'assets/image/bhotel/yugharling/1.webp',
        location: '',
        review: '',
        imgurl2: 'assets/image/bhotel/yugharling/2.webp',
        imgurl3: 'assets/image/bhotel/yugharling/3.webp',
        imgurl4: 'assets/image/bhotel/yugharling/4.webp'),

  ],
  [
    HotelClass(
        name: 'Amkora',
        abt: '',
        price: '',
        imgurl: 'assets/image/bhotel/amkora/1.webp',
        location: 'Bhumthang,Bhutan',
        review: '',
        imgurl2: 'assets/image/bhotel/amkora/2.webp',
        imgurl3: 'assets/image/bhotel/amkora/3.webp',
        imgurl4: 'assets/image/bhotel/amkora/4.webp'),
    HotelClass(
        name: 'Hotel Ugyenling',
        abt: '',
        price: '',
        imgurl: 'assets/image/bhotel/ugyenling/1.webp',
        location: 'Bhumthang,Bhutan',
        review: '',
        imgurl2: 'assets/image/bhotel/ugyenling/2.webp',
        imgurl3: 'assets/image/bhotel/ugyenling/3.webp',
        imgurl4: 'assets/image/bhotel/ugyenling/4.webp'),
    HotelClass(
        name: 'Valley Resort',
        abt: '',
        price: '',
        imgurl: 'assets/image/bhotel/valley/1.webp',
        location: 'Bhumthang,Bhutan',
        review: '',
        imgurl2: 'assets/image/bhotel/valley/2.webp',
        imgurl3: 'assets/image/bhotel/valley/3.webp',
        imgurl4: 'assets/image/bhotel/valley/4.webp'),
    HotelClass(
        name: ' Hotel Yugharling',
        abt: '',
        price: '',
        imgurl: 'assets/image/bhotel/yugharling/1.webp',
        location: '',
        review: '',
        imgurl2: 'assets/image/bhotel/yugharling/2.webp',
        imgurl3: 'assets/image/bhotel/yugharling/3.webp',
        imgurl4: 'assets/image/bhotel/yugharling/4.webp'),

  ],
  [
    HotelClass(
        name: 'Amkora',
        abt: '',
        price: '',
        imgurl: 'assets/image/bhotel/amkora/1.webp',
        location: 'Bhumthang,Bhutan',
        review: '',
        imgurl2: 'assets/image/bhotel/amkora/2.webp',
        imgurl3: 'assets/image/bhotel/amkora/3.webp',
        imgurl4: 'assets/image/bhotel/amkora/4.webp'),
    HotelClass(
        name: 'Hotel Ugyenling',
        abt: '',
        price: '',
        imgurl: 'assets/image/bhotel/ugyenling/1.webp',
        location: 'Bhumthang,Bhutan',
        review: '',
        imgurl2: 'assets/image/bhotel/ugyenling/2.webp',
        imgurl3: 'assets/image/bhotel/ugyenling/3.webp',
        imgurl4: 'assets/image/bhotel/ugyenling/4.webp'),
    HotelClass(
        name: 'Valley Resort',
        abt: '',
        price: '',
        imgurl: 'assets/image/bhotel/valley/1.webp',
        location: 'Bhumthang,Bhutan',
        review: '',
        imgurl2: 'assets/image/bhotel/valley/2.webp',
        imgurl3: 'assets/image/bhotel/valley/3.webp',
        imgurl4: 'assets/image/bhotel/valley/4.webp'),

  ],

];

