import '../doctor model/model_class.dart';

List<Modelclass>doclist = [
  Modelclass(name: 'Dr.Steven',
      imgUrl: 'assets/image/doctor1.png',
      specialilty: 'Lungs Specialist',
      payment: '\$40.00',
      patientNo: 200,
      experience: '6 yrs',
      rating: '4.6',
      appointmentDays: ['Mon-Thu','Sat'],
      appointmentTime: ['9:00 AM -5:00AM','9:00-1:00 PM'],
    aboutDoc: 'Dr.Steven is a Lungs specialist in RRG Hospital, Gelephu, Bhutan.He Has ton of experience in this field for serving the peoples '
  ), Modelclass(name: 'Dr.Lee Chung',
      imgUrl: 'assets/image/female_doc3.png',
      specialilty: 'Heart Specialist',
      payment: '\$70.00',
      patientNo: 165,
      experience: '7yrs',
      rating: '4.7',
      appointmentDays:['Mon-Thu','Sat'],
      appointmentTime: ['9:00 AM - 5:00 PM','9:00 - 1:00'],
      aboutDoc: 'Dr.lee is a Heart specialist in RRG Hospital, Gelephu, Bhutan.He Has ton of experience in this field for serving the peoples'
  ), Modelclass(name: 'Dr.Sus',
      imgUrl: 'assets/image/doctor2.png',
      specialilty: 'Chiro Specialist',
      payment: '\$30.00',
      patientNo: 200,
      experience: '5yrs',
      rating: '4.3',
      appointmentDays: ['Mon-Thu','Sat'],
      appointmentTime: ['9:00 AM - 5:00 PM','9:00 - 1:00'],
      aboutDoc: 'Dr.Sus is a Chiro specialist in RRG Hospital, Gelephu, Bhutan.He Has ton of experience in this field for serving the peoples'
  ), Modelclass(name: 'Dr.David',
      imgUrl: 'assets/image/doctor3.png',
      specialilty: 'Eye Specialist',
      payment: '\$40.00',
      patientNo: 200,
      experience: '4yrs',
      rating: '4.9',
      appointmentDays: ['Mon-Thu','Sat'],
      appointmentTime: ['9:00 AM - 2:00 PM','9:00 - 1:00'],
      aboutDoc: 'Dr.David is a Eye specialist in RRG Hospital, Gelephu, Bhutan.He Has ton of experience in this field for serving the peoples'
  ), Modelclass(name: 'Dr.Deepak',
      imgUrl: 'assets/image/doctor4.png',
      specialilty: 'Gaino Specialist',
      payment: '\$40.00',
      patientNo: 200,
      experience: '3yrs',
      rating: '4.9',
      appointmentDays: ['Mon-Fri','Sat'],
      appointmentTime: ['9:00 AM - 5:00 PM','9:00 - 1:00'],
      aboutDoc: 'Dr.Deepak is a Gaino specialist in RRG Hospital, Gelephu, Bhutan.He Has ton of experience in this field for serving the peoples'
  ),
];